library(MyoManager)

test_that("invalid input", {

  rabbit = loadImage(system.file('extdata/Rabbit_01.tif', package='MyoManager'))
  rNuc = selectFrame(rabbit, 3)
  df = getFeatureData(rNuc)

  random_df = mtcars
  random_matrix = matrix(rnorm(36),nrow=6)


  # Error in validImage(img) : EBImage object must be an array of pixel values.
  expect_error(countNuclei(fish))
  expect_error(getFeatureData(fish))

  expect_error(plotFeature(random_df, 'area'), "featureDF must be a data frame of features generated by featureData()")
  expect_error(plotFeature(random_matrix, 'area'), "featureDF must be a data frame of features generated by featureData()")
  expect_error(plotFeature(df), "please specify a morphological feature.")
  expect_error(plotFeature(df, 'sharpness'), "feature must be one of 'area', 'perimeter', 'radius', or 'roundness'.")

  expect_error(plotFeatureMatrix(random_df), "featureDF must be a data frame of features generated by featureData()")
  expect_error(plotFeatureMatrix(random_matrix), "featureDF must be a data frame of features generated by featureData()")

})

test_that("output plot format", {
  rabbit = loadImage(system.file('extdata/Rabbit_01.tif', package='MyoManager'))
  rNuc = selectFrame(rabbit, 3)
  df = getFeatureData(rNuc)
  plot = plotFeature(df, "area")
  matrix = plotFeatureMatrix(df)

  expect_true(ggplot2::is.ggplot(plot))
  expect_equal(matrix$nrow, 4)
  expect_equal(matrix$ncol, 4)

})

#End
